### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Eli-Black-Work** [xtuc/mamacro#2]
Hello,

Could you please add a LICENSE file to the project? Thanks :)

**Comment by xtuc** [comment]
This is an internal project, I don't want to maintain it nor that people use it.

**Comment by Eli-Black-Work** [comment]
Hi @xtuc. The problem is that mamacro is a dependency for @webassemblyjs/ast, which is a dependency for webpack, so mamacro ends up being a sub-sub-dependency for a lot of projects.

**Comment by xtuc** [comment]
It's a bug https://github.com/xtuc/webassemblyjs/blob/master/packages/ast/package.json#L18 should be in devDependecies.

**Comment by Eli-Black-Work** [comment]
Ah, okay, thanks. I see you opened a bug in the webassemblyjs project; appreciate it :)

**Comment by kuba-kubula** [comment]
Hi everyone. Unfortunately `webassemblyjs` AST depends in its `src` on `mamacro`, so it can't be moved to `devDependencies` easily, even though it would be the possible solution on first-sight.

I guess another, and IMHO probably correct, approach would be to release `mamacro` and `babel-plugin-mamacro` with newer version of `lerna` (3.x), where the `LICENSE` files would be distributed alongside each of those two `packages`. But that would assume there is a `LICENSE` file in the source repository – which is not the case here.

**Comment by xtuc** [comment]
`mamacro` is transpiled out of the source during the build, you can look at the actual implementation of `mamacro`. 

It should be in devDependecies because it's not used in production.

**Comment by char0n** [comment]
Provided PR how webasembly/ast uses mamacro here: https://github.com/xtuc/webassemblyjs/issues/453

Anyway this doesn't change the situation. Mamacro doesn't have a license and without it, it is a proprietary code and we cannot download it nor install it as part of devDependencies.
